Array from data

In [8]:
import numpy as np

In [9]:
array_from_list = np.array([1, 2, 3])
array_from_list

array([1, 2, 3])

In [4]:
list_a = [1, 2 ,3]
type(list_a)

list

In [6]:
array_from_list = np.array(list_a)
array_from_list
type(array_from_list)

numpy.ndarray

In [7]:
tuple_a = (1, 2, 3)
type(tuple_a)

tuple

In [10]:
array_from_tuple = np.array(tuple_a)
print(array_from_tuple)
print(type(array_from_tuple))

[1 2 3]
<class 'numpy.ndarray'>


In [11]:
array_from_list + 5

array([6, 7, 8])

In [12]:
array_from_tuple + 5

array([6, 7, 8])

In [13]:
set_a = {1, 2, 3, 4}
print(set_a)
print(type(set_a))

{1, 2, 3, 4}
<class 'set'>


In [14]:
array_from_set = np.array(set_a)
array_from_set

array({1, 2, 3, 4}, dtype=object)

In [15]:
dict_a = {1: 'a', 2:'b'}
print(dict_a)
print(type(dict_a))

{1: 'a', 2: 'b'}
<class 'dict'>


In [16]:
array_from_dict = np.array(dict_a)
array_from_dict

array({1: 'a', 2: 'b'}, dtype=object)